version: '3.9'

services:
  db:
    image: postgres:15
    container_name: superhero-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: superheroes
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: superhero-backend
    restart: always
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/superheroes?schema=public'
      PORT: 4000
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: superhero-frontend
    restart: always
    ports:
      - '5174:5174'
    environment:
      VITE_API_URL: 'http://backend:4000/api'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  pgdata:
